# Generated by Django 4.0.4 on 2022-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='altura',
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
