# Generated by Django 4.0.4 on 2022-05-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_remove_persona_altura_persona_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Empleado',
        ),
    ]
