# Generated by Django 4.0.4 on 2022-05-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_rename_persona_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Persona',
        ),
    ]
