# Generated by Django 4.0.4 on 2022-05-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0006_rename_empleado_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Empleado',
        ),
    ]
