# Generated by Django 4.0.4 on 2022-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0007_rename_persona_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('cuit_empresa', models.IntegerField()),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('cargo_contacto', models.CharField(max_length=100)),
                ('cobro_mensual_honorarios', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
