# Generated by Django 4.0.4 on 2022-05-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0008_clientes_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
