# Generated by Django 4.0.4 on 2022-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0009_rename_clientes_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_de_trabajo', models.DateField()),
                ('horas_trabajadas', models.FloatField(default=0.0)),
                ('promedio_precio_hora', models.FloatField(default=0.0)),
            ],
        ),
    ]
