# Generated by Django 4.0.4 on 2022-05-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0010_horascliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horascliente',
            name='promedio_precio_hora',
        ),
    ]
